name: build_with_docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    env:
     DOCKER_USERNAME: ${{ secrets.USERNAME }}
     DOCKER_PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
         sudo docker build -t blog:last --file ${{ secrets.DOCKERFILE }} .
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ secrets.USERNAME }}/newblog:${{ github.ref_name }}
            ${{ secrets.USERNAME }}/newblog:latest
      - name: Run Docker container
        run: |
         sudo docker run --name newblog -p 5980:80 ${{ secrets.USERNAME }}/newblog:latest




        
  
  
