name: build_with_docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    env:
     DOCKER_USERNAME: ${{ secrets.USERNAME }}
     DOCKER_PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: login aliyun
        run: |
         sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hongkong.aliyuncs.com
      - name: Build Docker Image
        run: |
         sudo docker build -t blog:last --file ${{ secrets.DOCKERFILE }} .
      - name: Build and push ALI
        id: ALI_build
        run: |
          sudo docker ${{ secrets.USERNAME }}/newblog registry.cn-hongkong.aliyuncs.com/sdwyg/blogo:latest
          sudo docker push registry.cn-hongkong.aliyuncs.com/sdwyg/blogo:latest
      - name: Run Docker container
        run: |
         sudo docker run --name newblog -p 5980:80 ${{ secrets.USERNAME }}/newblog:latest




        
  
  
