name: build_cd

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: login aliyun
        run: |
          sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hongkong.aliyuncs.com
      
      - name: Build Docker Image
        run: |
          image_name="${{ secrets.USERNAME }}/newblog"
          tag_name="${{IMAGETAG}}"
          if docker images | grep $image_name:$tag_name > /dev/null; then
           docker rmi $image_name:$tag_name
          fi
          sudo docker build -t $image_name:$tag_name -f ${{ secrets.DOCKERFILE }} .

      - name: Build and push ALI
        id: ALI_build
        run: |
          image_name="${{ secrets.USERNAME }}/newblog"
          sudo docker tag  $image_name:latest registry.cn-hongkong.aliyuncs.com/sdwyg/blogo:latest
          sudo docker push registry.cn-hongkong.aliyuncs.com/sdwyg/blogo:latest

