name: build_with_docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Docker_File: ${{ secrets.MY_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -t blog:last --file ${{ secrets.DOCKERFILE }} .
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.PASSWORD }}
          password: ${{ secrets.USERNAME }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/NewBlog:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/NewBlog:latest


        
  
  
